### ISSUE TITLE
 requires magento/module-backend not found

### ISSUE THREAD

**Issue by anethum** [magepal/magento2-reindex#10]
Hello I get following Error during the installation.

magepal/magento2-reindex 1.0.8 requires magento/module-backend 100.0.*|100.1.*|100.2.*|101.0.* -> no matching package found.

#### Magento version #:
Magento 2.3.5-p1

#### Preconditions
PHP version (7.3.18)

**Comment by srenon** [comment]
Magento 2.3.5-pi has a backend version of 101.0.5 which is satisfied by our composer requirement 

![image](https://user-images.githubusercontent.com/1415141/83409833-3a587200-a3e3-11ea-8825-5bd1ab271f80.png)
