### ISSUE TITLE
Stuck indexes with larger datasets

### ISSUE THREAD

**Issue by SamJUK** [magepal/magento2-reindex#11]
#### Overview
We have this module installed on a client site and for the most part, it works fine while reindexing single indexes. Whenever the client performs mass indexes we are seeing an increase in stuck indexes, caused by the Nginx+PHP-FPM workers timing out.

Adding a feature flag to toggle between the existing Synchronous processing and a new Async mode would alleviate this issue. Which could be achieved by defering the reindex & picking up by a cron, or spawning a new background task that calls Magento's CLI indexer commands.

#### Magento version #: 
Magento 2.3.5

#### Edition (EE, CE, OS, etc): 
Community Edition

#### Expected behavior:
Able to reindex all indexes are once successfully. 

#### Actual behavior:
Page times out and Indexes get stuck processing on Catalog Rule

#### Steps to reproduce:
1. Trigger full reindex from the backend

#### Preconditions
PHP: 7.2
Mage: 2.3.5 : CE
Mode: Production
Average size store: ~35k Products

**Comment by srenon** [comment]
@SamJUK ... this should be one of the main reason Magento removed this feature

![image](https://user-images.githubusercontent.com/1415141/88056418-80ea6300-cb2e-11ea-8317-674942ad08aa.png)

We think about creating a new extension that will trigger by cron, but I know of users who crash their site trying to run command line reindex during a major sales

**Comment by SamJUK** [comment]
@srenon, Our Client is pretty adamant of having this functionality. 

Would you guys be willing it merge a pull request that abstracts out the current reindex method to a model so we can overwrite it easier? 
https://github.com/magepal/magento2-reindex/blob/master/Controller/Adminhtml/Indexer/ReindexOnTheFly.php#L44:L47

Or even a PR that introduces Async indexing?

**Comment by srenon** [comment]
Sure, create a PR and we will review it...

If you have a large site and you trying to reindex Async won't that basically kill your DB server?  

I'm thinking about creating an option were in system config you can choose which indexing option you want to apply (similar to full page cache)

**Comment by SamJUK** [comment]
Async is probably the wrong term for it since we are not running the indexes in parallel. 
But deferring the task into a message queue that can be picked up by a consumer. 

For selecting what reindex strategy to use, I've added a dropdown to the system config like how the Search Engine works. Allowing for easy extension by adding new strategies via XML. 

I'll create a PR in a few minutes for it. Functionally it's there, I just need to tidy up some of the code and test against a clone of our live environment.
