### ISSUE TITLE
Invalid foreign key while reindexing Customer Grid

### ISSUE THREAD

**Issue by timleeuchees** [magepal/magento2-reindex#2]
Hi,

When I want to reindex customer grid directly from backend, it shows "Invalid foreign key" as below image:
https://prnt.sc/i2hda0

I execute reindex from command line:
php bin/magento indexer:reindex customer_grid

Also got the same error:
Invalid foreign key

Do you know how to fix this issue? Thanks.
My Magento version is: 2.1.8

Tim

**Comment by srenon** [comment]
@timleeuchees ... this issue is not caused by this module

**Comment by timleeuchees** [comment]
@srenon Thanks and I'll check other modules.
