### ISSUE TITLE
Shipping Coupon not working with this extension

### ISSUE THREAD

**Issue by asharjanjua** [magepal/magento2-reindex#3]

**Comment by srenon** [comment]
@asharjanjua ... could you provide more info?

![image](https://user-images.githubusercontent.com/1415141/45050965-a6f8de00-b050-11e8-93f1-45f0f0f7959b.png)

**Comment by asharjanjua** [comment]
I installed this extension. After that i setup cart rules for free
shipping. I created a copoun in Marketing -> cart Price Rule . On checkout
page when i select custom shipping rated of this extension and apply a
coupon then nothing happens. coupon donot reduce shipping price.

**Comment by asharjanjua** [comment]
sorry i opened thread on wrong extension
